---
- import_playbook: trinity-image-setup.yml
  vars:
    hostlist: ood

- hosts: ood
  roles:

    - role: trinity/ood-portal
      slurm_controller: '{{ trix_ctrl_hostname }}'
      ldap_hosts: 
        - '{{ trix_ctrl_hostname }}.{{ trix_domain }}'
      login_host: '{{ trix_ctrl_hostname }}'
      tags: ood
- hosts: vncnodes
  roles:
  - role: trinity/graphical_desktop
    tags: graphical_desktop

- hosts: controllers
  roles:
    - role: trinity/ood-modules
      tags: ood-modules
      

    
