---
- name: create a mountpoint for the shared file system
  file:
    path: '{{ aws.sharedfs_mountpoint }}'
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: mount the shared file system
  mount:
    src: '{{ aws.sharedfs_ip }}:/'
    path: '{{ aws.sharedfs_mountpoint }}'
    opts: 'nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport'
    fstype: nfs4
    state: mounted
  when: use_shared_blockdev

#- name: rename default /trinity dir
#  shell: 'mv {{ trix_root }} {{trix_root }}-bkp'
#  args:
#    creates: '{{ trix_root }}-bkp'

- name: locate the EBS shared device
  shell: lsblk  -fnpl | grep -A1 xfs | grep -v xfs | awk '{ print $1 }'
  register: blockdev
  changed_when: false

- name: format the shared block device
  filesystem:
    fstype: xfs
    dev: '{{ blockdev.stdout }}'

- name: get the shared block device UUID
  shell: blkid | grep '{{ blockdev.stdout }}' | awk '{ print $2 }' | tr -d '"'
  register: blockdev_uuid
  changed_when: false

- name: mount the shared block device on '{{ trix_root }}'
  mount:
    src: '{{ blockdev_uuid.stdout }}'
    path: '{{ trix_root }}'
    fstype: xfs
    state: mounted

#- name: copy '{{ trix_root }}-bkp' to '{{ trix_root }}'
#  shell: 'rsync -raW -AX {{ trix_root }}-bkp/* {{ trix_root }}/'
#  args:
#    creates: '{{ trix_root }}/local'
