---
# tasks file for ood-portal
- name: Install centos-release-scl repo
  yum:
    name: centos-release-scl
    state: present

- name: Install OOD Repo rpm
  yum:
    name: https://yum.osc.edu/ondemand/1.6/ondemand-release-web-1.6-1.el7.noarch.rpm
    state: present

- name: Install OOD
  yum:
    name: ondemand
    state: present

- name: Ensure ood config paths exist
  file:
    path: '{{ item }}'
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - '/etc/ood/config/'
    - '/etc/ood/config/clusters.d'
    - '/etc/ood/config/apps'
    - '/etc/ood/config/apps/bc_desktop'

- name: Render ood_portal config file
  template:
    src: 'ood_portal.yml'
    dest: '{{ ood_portal_cfg_path }}/ood_portal.yml'
    mode: '0644'
    owner: root
    group: root
- name: Render ood_portal cluster config file
  template:
    src: 'cluster_definition.yml'
    dest: '{{ ood_portal_cfg_path }}/clusters.d/{{ cluster_name }}.yml'
    mode: '0644'
    owner: root
    group: root

- name: Render ood_portal remote_desktop config file
  template:
    src: 'bc_desktop_definition.yml'
    dest: '{{ ood_portal_cfg_path }}/apps/bc_desktop/{{ cluster_name }}.yml'
    mode: '0644'
    owner: root
    group: root
  when: enable_vnc_to_nodes == true

- name: run update_ood_portal to generate webserver config file
  command: '/opt/ood/ood-portal-generator/sbin/update_ood_portal'
  register: command_result
  failed_when: "'Completed successfully!' not in command_result.stdout"

- name: enable ood webserver by default
  service:
    name: httpd24-httpd
    enabled: yes

- name: (re)start ood webserver
  service:
    name: httpd24-httpd
    state: restarted