---
#- name: Display all variables/facts known for a host
#  debug:
#    var: hostvars[inventory_hostname]

- name: Create trinity/ohpc dir for opt link to point at
  file:
    path: '{{ trix_ohpc }}'
    owner: root
    group: root
    state: directory
    mode: '0755'
  when: '"controllers" in group_names'

- name: Create link so openhpc ends up on /trinity filesystem so that config data is not lost on an instance rebuild
  file:
    src: '{{ trix_ohpc }}'
    path: /opt/ohpc
    owner: root
    group: root
    state: link
  when: ansible_connection not in 'lchroot' and "controllers" in group_names


- name: Install ohpc-release
  yum:
    name: https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm
    state: installed

- name: Ensure conflicting rpms from legacy TrinityX are not installed
  yum:
    name:
      - pdsh
      - environment-modules
    state: removed

- name: Install ohpc-base
  yum:
    name: ohpc-base
    state: installed
  when: ansible_connection not in 'lchroot' and "controllers" in group_names

- name: Install ohpc-base-compute
  yum:
    name: ohpc-base-compute
    state: installed
  when: ansible_connection not in 'lchroot' and "controllers" in group_names

- name: Install lmod dependencies on non-controller nodes
  yum:
    name:
      - lua-filesystem-ohpc
      - lua-posix-ohpc
    state: installed
  when: ansible_connection not in 'lchroot' and "controllers" in group_names

#todo copy /etc/profile.d/lmod.* to provisioning node from controller and copy it back out to computes


- name: Install lmod-ohpc
  yum:
    name: lmod-ohpc
    state: installed
  when: ansible_connection not in 'lchroot' and "controllers" in group_names


- name: Update NFS exports
  template:
    src:  OHPC_exports
    dest: '{{ nfs_exports_path }}/ohpc.exports'
  when: primary | default(True) and ansible_connection not in 'lchroot'
  notify:
    - Export NFS

#- file:
#    src: '{{ nfs_exports_path }}/ohpc.exports'
#    dest: '/etc/exports.d/ohpc.exports'
#    state: link
#    force: yes
#  when: primary | default(True) and ansible_connection not in 'lchroot'
#  notify:
#    - Export NFS
